In [1]:
import pandas as pd
import numpy as np

raw_data = {
    'Full_Name': ['Krish', 'Amit Shah', 'Priya Patel', 'Rahul V.', 'Sanya M.', 'CEO_Dave', 'Anjali R.', 'Deepak K.'],
    'Role': ['ML Engineer', 'ml engineer', 'Data Scientist', 'data scientist', 'ML Eng', 'Founder', 'Data Scientist', 'ML Engineer'],
    'Experience_Years': [1, 3, 5, np.nan, 2, 20, 4, 1],
    'Location': ['Ahmedabad', 'Ahmedabad', 'Bangalore', 'Bangalore', 'Ahmedabad', 'Mumbai', 'Mumbai', 'Ahmedabad'],
    'Salary_INR': [1200000, 1300000, 1800000, 1750000, 1100000, 95000000, 1600000, 1250000]
}

df = pd.DataFrame(raw_data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Full_Name         8 non-null      object
 1   Role              8 non-null      object
 2   Experience_Years  7 non-null      float64
 3   Location          8 non-null      object
 4   Salary_INR        8 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 452.0+ bytes

In [2]:
df.describe()

       Experience_Years    Salary_INR
count          7.000000  8.000000e+00
mean           5.142857  1.312500e+07
std            6.718843  3.308353e+07
min            1.000000  1.100000e+06
25%            1.500000  1.237500e+06
50%            3.000000  1.450000e+06
75%            4.500000  1.762500e+06
max           20.000000  9.500000e+07

In [3]:
df['Role'].value_counts()

Role
ML Engineer       2
Data Scientist    2
ml engineer       1
data scientist    1
ML Eng            1
Founder           1
Name: count, dtype: int64

In [4]:
df["Role"]=df["Role"].str.lower().str.replace("engineer","eng").str.strip()
print(df["Role"])

0            ml eng
1            ml eng
2    data scientist
3    data scientist
4            ml eng
5           founder
6    data scientist
7            ml eng
Name: Role, dtype: object

In [6]:
import numpy as np
m=df["Experience_Years"].median()
df["Experience_Years"] = df["Experience_Years"].fillna(m)
df["Experience_Years"]

0     1.0
1     3.0
2     5.0
3     3.0
4     2.0
5    20.0
6     4.0
7     1.0
Name: Experience_Years, dtype: float64

In [7]:
from sklearn.preprocessing import RobustScaler
robust_s_value=RobustScaler()
new_df=pd.DataFrame(robust_s_value.fit_transform(df[["Salary_INR"]]))
df["Salary_INR"]=new_df
print(df)

     Full_Name            Role  Experience_Years   Location  Salary_INR
0        Krish          ml eng               1.0  Ahmedabad   -0.476190
1    Amit Shah          ml eng               3.0  Ahmedabad   -0.285714
2  Priya Patel  data scientist               5.0  Bangalore    0.666667
3     Rahul V.  data scientist               3.0  Bangalore    0.571429
4     Sanya M.          ml eng               2.0  Ahmedabad   -0.666667
5     CEO_Dave         founder              20.0     Mumbai  178.190476
6    Anjali R.  data scientist               4.0     Mumbai    0.285714
7    Deepak K.          ml eng               1.0  Ahmedabad   -0.380952

In [8]:
df_encode=pd.get_dummies(df,drop_first=True,columns=["Role","Location"])
df_encode

,Full_Name,Experience_Years,Salary_INR,Role_founder,Role_ml eng,Location_Bangalore,Location_Mumbai
0,Krish,1.0,-0.476190,False,True,False,False
1,Amit Shah,3.0,-0.285714,False,True,False,False
2,Priya Patel,5.0,0.666667,False,False,True,False
3,Rahul V.,3.0,0.571429,False,False,True,False
4,Sanya M.,2.0,-0.666667,False,True,False,False
5,CEO_Dave,20.0,178.190476,True,False,False,True
6,Anjali R.,4.0,0.285714,False,False,False,True
7,Deepak K.,1.0,-0.380952,False,True,False,False

In [9]:
from sklearn.model_selection import train_test_split
X=df_encode.drop(['Salary_INR', 'Full_Name'], axis=1)
y=df_encode["Salary_INR"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)

(6, 5)
(2, 5)